### ISSUE TITLE
[오늘의 메뉴] 햄버거 이슈 의논

### ISSUE THREAD

**Issue by ckkim817** [GEON-PPANG/GEON_PPANG_PLAN#4]
16:30에 햄버거 시키기로 했습니다 (14:30경 집에 있었던 사람들끼리)

가게는 버거킹 or 프랭크버거 고민 중이고 제가 시키겠습니다

드실 분 댓글에 영역 표시해주시면 감사티비

**Comment by seongmin221** [comment]
**쉐이킹프라이 매콤치즈** ~ 에 창균이 음료 뺏어먹기 !

**Comment by Dan2dani** [comment]
다은, 지현: 통새우와퍼 단품 + 프렌치프라이 L

**Comment by seunghaLim** [comment]
승하: 바삭킹 8조각인가 6조각인가 암튼그거 사이드
성은: 와퍼주니어 세트
